M48
; DRILL file {KiCad (6.0.2)} date Fri Apr 14 14:35:22 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-14T14:35:22-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X2.7Y-3.6
X2.7Y-4.3
X2.9Y-3.5
X2.9Y-3.8
X2.9Y-4.3
X2.9553Y-3.9053
X3.0Y-3.3
X3.1Y-3.3
X3.1Y-3.8
X3.2Y-3.9
X3.5Y-3.6
X3.5Y-3.7
T2
X3.0Y-3.2
X3.0984Y-3.2
T0
M30
